plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
plot(temp,temp,type="n",ylab="",xlab="",main="",axes=FALSE)
dev.off()
